[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:bridge]
directory=/app/Bridge
command=node server.js
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true


[program:python]
directory=/app
command=uvicorn main:app --host=0.0.0.0 --port=3000
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true